spring:
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/config/,classpath:/mapper/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /api
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

